### ISSUE TITLE
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:doc_cons, "&", "1"}

### ISSUE THREAD

**Issue by ZhengQingchen** [lpil/exfmt#4]
I try exfmt code like this:

```
defmodule Example do
  def get_tags() do
    [%{name: 1}, %{name: 2}]
    |> Enum.map(& &1.name)
  end
end
```

got this error: 

```
➜  exfmt git:(master) ✗ mix exfmt my_ex.ex
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:doc_cons, "&", "1"}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/exfmt/ast/to_algebra.ex:234: Exfmt.Ast.ToAlgebra.to_algebra/2
    lib/exfmt/ast/to_algebra.ex:106: Exfmt.Ast.ToAlgebra.to_algebra/2
    (elixir) lib/inspect/algebra.ex:559: Inspect.Algebra.do_surround_many/7
    lib/exfmt/ast/to_algebra.ex:349: Exfmt.Ast.ToAlgebra.call_to_algebra/3
    lib/exfmt/ast/to_algebra.ex:356: Exfmt.Ast.ToAlgebra.infix_child_to_algebra/3
    lib/exfmt/ast/to_algebra.ex:160: Exfmt.Ast.ToAlgebra.to_algebra/2
```

I think is ```Enum.map(& &1.name)```  the ```& &```  make error happen.

**Comment by lpil** [comment]
Thanks for the report! Currently not all forms can be rendered, but I'm hoping to have them all soon. I'll push support for this form later today.
