### ISSUE TITLE
(Protocol.UndefinedError) protocol String.Chars not implemented for {:doc_cons, "conn", ".assigns"}

### ISSUE THREAD

**Issue by udfalkso** [lpil/exfmt#8]
```
$ mix exfmt web/controllers/list_controller.ex 
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:doc_cons, "conn", ".assigns"}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/exfmt/ast/to_algebra.ex:277: Exfmt.Ast.ToAlgebra.to_algebra/2
    lib/exfmt/ast/to_algebra.ex:413: Exfmt.Ast.ToAlgebra.infix_child_to_algebra/3
    lib/exfmt/ast/to_algebra.ex:199: Exfmt.Ast.ToAlgebra.to_algebra/2
    lib/exfmt/ast/to_algebra.ex:342: Exfmt.Ast.ToAlgebra.keyword_to_algebra/2
    (elixir) lib/inspect/algebra.ex:576: Inspect.Algebra.do_surround_many/5
    (elixir) lib/inspect/algebra.ex:559: Inspect.Algebra.do_surround_many/7
```

I managed to trim the controller down to this small snippet that causes the crash above to present itself:
```
defmodule Normal.ListController do

  def show(conn, %{"slug" => slug} = params) do
    posts = Normal.Data.Posts.by_list_slug(slug, safe_only: conn.assigns[:safe_mode_active])
  end

end
```

**Comment by lpil** [comment]
Thanks for the report! :)

**Comment by lpil** [comment]
This is the problem here:

```elixir
conn.assigns[:safe_mode_active]
```

I'm not rendering the access protocol safely at the moment.
